name: opi-lab-regression
on: workflow_dispatch
jobs:
  opi-lab-job:
    runs-on: self-hosted
    steps:
        - uses: actions/checkout@v1
        - name: pytest-run1
          run: ls
        - name: pytest-run2
          run: pwd
        - name: pytest-run3
          run: pip install -r ./demos/tgen/requirements.txt
        # - name: load 1password secrets
        #   uses: 1password/load-secrets-action@v1
        #   with:
        #     export-env: true 
        #   env:
        #     OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        #     SERVER_IP: op://opi-lab/tgen1/URL
        #     SERVER_USER: op://opi-lab/tgen1/username
        #     SERVER_PASS: op://opi-lab/tgen1/password
        - name: get-pass
          env:
            ROOT_PASSWORD: ${{ secrets.ROOT_PASSWORD }}
        - name: pytest-run4
          run: pytest -s ./demos/tgen/test_tgen_demo.py
        # - name: pytest-run5
        #   run: pytest -s ./demos/tgen/test_tgen_demo.py
